on:
  push:
    branches:
      - main # 触发分支

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      # - name: Check commit message
      # if: contains(github.event.head_commit.message, '[deploy]') == false
      # run: |
      #   echo "Not found keyword '[Deploy]' in commit message. Exiting workflow."
      #   exit 0
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies and build
        run: |
          npx pnpm install
          npx pnpm run build

      - name: Compressed file
        run: |
          tar -czf dist.tar.gz .output

      - name: Copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          source: dist.tar.gz
          target: /www/wwwroot/Nuxt3/nuxt3-health-admin

      - name: Exec commands
        run: |
          cd ${{secrets.SERVER_PATH }}
          rm -rf public/ server/ nitro.json
          tar -xzf dist.tar.gz
          # rm dist.tar.gz
