on:
  push:
    branches:
      - main # 触发分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Check commit message
        if: contains(github.event.head_commit.message,'[deploy]') == false
        run: |
          echo "Not found keyword '[Deploy]' in commit message. Exiting workflow."
          exit 0

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        run: |
          curl -fsSL https://get.pnpm.io/install.sh | sh
          export PATH="$HOME/.pnpm/bin:$PATH"

      - name: Install dependencies and build
        run: |
          pnpm install
          pnpm run build
          tar -czf dist.tar.gz .output

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: dist.tar.gz
          target: /dist.tar.gz
