on:
  push:
    branches:
      - main # 触发分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      # - name: Check commit message
      # if: contains(github.event.head_commit.message, '[deploy]') == false
      # run: |
      #   echo "Not found keyword '[Deploy]' in commit message. Exiting workflow."
      #   exit 0

      # - name: Checkout code
      #   uses: actions/checkout@v4

      # - name: Install dependencies and build
      #   run: |
      #     npx pnpm install
      #     npx pnpm run build

      # - name: zip
      #   run: |
      #     tar -czf build.tar.gz .output

      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Add SSH key to known hosts
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/id_rsa && chmod 600 $HOME/.ssh/id_rsa && ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> $HOME/.ssh/known_hosts

      # - name: Transfer build to server
      #   run: scp -i ~/.ssh/id_rsa -P ${{ secrets.SERVER_PORT }} build.tar.gz ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/path/on/server/

      - name: SSH into server and extract build
        run: |
          ssh -i $HOME/.ssh/id_rsa ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}
