on:
  push:
    branches:
      - main # 触发分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      # - name: Check commit message
      # if: contains(github.event.head_commit.message, '[deploy]') == false
      # run: |
      #   echo "Not found keyword '[Deploy]' in commit message. Exiting workflow."
      #   exit 0

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies and build
        run: |
          npx pnpm install
          npx pnpm run build
          tar -czf dist.tar.gz .output

      - name: Upload build to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          source: build.tar.gz
          target: /

      - name: SSH into server and extract build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            # cd /path/on/server/
            tar -xzf build.tar.gz
            rm build.tar.gz
